### ISSUE TITLE
Error "wac create --company Microsoft --tool Foo --solution MySolution --version next"

### ISSUE THREAD

**Issue by limulidae** [Microsoft/windows-admin-center-extension-template#35]
./MySolution
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, copyfile 'C:\Users\limulidae\AppData\Roaming\npm\node_modules\windows-admin-center-cli\templates\upgrade\package.json' -> './MySolution\package.json'
    at Object.copyFileSync (fs.js:1724:3)
    at create (C:\Users\limulidae\AppData\Roaming\npm\node_modules\windows-admin-center-cli\src\index.js:83:8)
    at createExtension (C:\Users\limulidae\AppData\Roaming\npm\node_modules\windows-admin-center-cli\src\index.js:46:3)

**Comment by mattatmsft** [comment]
Hi Limulidae - 

This should be fixed if you install the "next" version of the CLI.  NPM I -g windows-admin-center-cli@next

Let me know if that works!
